services:
  app:
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que solo esté el nombre del archivo aquí
    ports:
      - "8080:8080"
    volumes:
      - "//C/Users/Albeto/Parcial1/identifier.sqlite:/app/identifier.sqlite"
